services:
  api:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      # protect container-installed node_modules from being clobbered by your host
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy   # wait for MySQL to be fully ready
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ptcpokemon
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    # you only need this if you want to hit MySQL directly from your host
    # remove it if you only ever connect via the api container
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped

volumes:
  dbdata:

networks:
  app-network:
